name: gizter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

# flutter_native_splash
flutter_native_splash:
  color: "#F9F9F9"
  image: assets/png/splash-text-logo.png

  android_12:
    image: assets/png/splash-text-logo.png
    icon_background_color: "#F9F9F9"

  web: false
