name: gizter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.15
  flutter_launcher_icons: ^0.11.0
  flutter_riverpod: ^2.1.1
  firebase_core: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

# flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/app-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/png/app-icon.png"
  windows:
    generate: true
    image_path: "assets/png/app-icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/png/app-icon.png"

# flutter_native_splash
flutter_native_splash:
  color: "#F9F9F9"
  image: assets/png/splash-text-logo.png

  android_12:
    image: assets/png/splash-text-logo.png
    icon_background_color: "#F9F9F9"

  web: false
