// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZGHKdyVtDvmZxo33c_OV96ZYzfe4f0cY',
    appId: '1:80374075731:web:c0eca7080378a7914f51a6',
    messagingSenderId: '80374075731',
    projectId: 'gizter-d5064',
    authDomain: 'gizter-d5064.firebaseapp.com',
    storageBucket: 'gizter-d5064.appspot.com',
    measurementId: 'G-5XQEND6P5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB15XNB_F2ut6WfL73COa9UHuyzw2vxhHM',
    appId: '1:80374075731:android:fdaa88df149e5eaa4f51a6',
    messagingSenderId: '80374075731',
    projectId: 'gizter-d5064',
    storageBucket: 'gizter-d5064.appspot.com',
  );
}
